#-----------------------------------------
# Continuous integration with Travis CI
# http://docs.travis-ci.com/
#	
# Configuration file
#-----------------------------------------

sudo: required
dist: trusty
os: linux

branches: 
  only: 
    - master

# overwriting default 'Ruby' by 'C' environment
# which does not affect Red language script execution
language: c

before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update

install: 
  - sudo apt-get install -y libc6:i386 libcurl3:i386
  - sudo chmod +x red-063-linux
  - ./red-063-linux --compile --release --output travis-tests run-all-tests.red

# CLI red console always returns EXIT code: 0
# so the only way to catch EXIT code is running a compiled version of run-all-tests.red
# compiled binary works as expected (0 - success, 1 - failure)
script: ./travis-tests
